//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePassWindows {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnePassWindows.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Generation Area (click to copy) 的本地化字符串。
        /// </summary>
        internal static string code_generate_area {
            get {
                return ResourceManager.GetString("code_generate_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DC 的本地化字符串。
        /// </summary>
        internal static string code_number {
            get {
                return ResourceManager.GetString("code_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Memory Password you entered this time is different from the Memory Password you entered last time. Please check if the input is correct. We recommend using the same memory password to avoid problems with forgotten passwords and memory confusion. 的本地化字符串。
        /// </summary>
        internal static string different_password_msg {
            get {
                return ResourceManager.GetString("different_password_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First Capital Letter 的本地化字符串。
        /// </summary>
        internal static string first_capital_letter {
            get {
                return ResourceManager.GetString("first_capital_letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GET 的本地化字符串。
        /// </summary>
        internal static string get {
            get {
                return ResourceManager.GetString("get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INPUT 的本地化字符串。
        /// </summary>
        internal static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MP 的本地化字符串。
        /// </summary>
        internal static string memory_password {
            get {
                return ResourceManager.GetString("memory_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Source 的本地化字符串。
        /// </summary>
        internal static string open_source {
            get {
                return ResourceManager.GetString("open_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password Length 的本地化字符串。
        /// </summary>
        internal static string password_length {
            get {
                return ResourceManager.GetString("password_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length[ 的本地化字符串。
        /// </summary>
        internal static string password_length_value {
            get {
                return ResourceManager.GetString("password_length_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remember Memory Password 的本地化字符串。
        /// </summary>
        internal static string remember_password {
            get {
                return ResourceManager.GetString("remember_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Password 的本地化字符串。
        /// </summary>
        internal static string show_password {
            get {
                return ResourceManager.GetString("show_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password: 的本地化字符串。
        /// </summary>
        internal static string strong_password {
            get {
                return ResourceManager.GetString("strong_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 · Memory Password: Choose a simple password. 的本地化字符串。
        /// </summary>
        internal static string use_explanation1 {
            get {
                return ResourceManager.GetString("use_explanation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 · Distinctive Code: The purpose of the password, such as Facebook account can be used as &quot;Facebook&quot; or &quot;FB&quot;. 的本地化字符串。
        /// </summary>
        internal static string use_explanation2 {
            get {
                return ResourceManager.GetString("use_explanation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Special Symbol 的本地化字符串。
        /// </summary>
        internal static string with_character {
            get {
                return ResourceManager.GetString("with_character", resourceCulture);
            }
        }
    }
}
