//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePassWindows {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnePassWindows.Resource.zh_CN", typeof(Resource_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 密码生成区(点击复制) 的本地化字符串。
        /// </summary>
        internal static string code_generate_area {
            get {
                return ResourceManager.GetString("code_generate_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区分代号 的本地化字符串。
        /// </summary>
        internal static string code_number {
            get {
                return ResourceManager.GetString("code_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您此次输入的记忆密码与最近一次输入的记忆密码不同，请检查一下输入是否正确。我们建议使用相同的记忆密码，以避免出现忘记密码、记忆混乱的问题。 的本地化字符串。
        /// </summary>
        internal static string different_password_msg {
            get {
                return ResourceManager.GetString("different_password_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首位大写字母 的本地化字符串。
        /// </summary>
        internal static string first_capital_letter {
            get {
                return ResourceManager.GetString("first_capital_letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取 的本地化字符串。
        /// </summary>
        internal static string get {
            get {
                return ResourceManager.GetString("get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入 的本地化字符串。
        /// </summary>
        internal static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记忆密码 的本地化字符串。
        /// </summary>
        internal static string memory_password {
            get {
                return ResourceManager.GetString("memory_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开源地址 的本地化字符串。
        /// </summary>
        internal static string open_source {
            get {
                return ResourceManager.GetString("open_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码长度 的本地化字符串。
        /// </summary>
        internal static string password_length {
            get {
                return ResourceManager.GetString("password_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码长度[ 的本地化字符串。
        /// </summary>
        internal static string password_length_value {
            get {
                return ResourceManager.GetString("password_length_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住记忆密码 的本地化字符串。
        /// </summary>
        internal static string remember_password {
            get {
                return ResourceManager.GetString("remember_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置 的本地化字符串。
        /// </summary>
        internal static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示密码 的本地化字符串。
        /// </summary>
        internal static string show_password {
            get {
                return ResourceManager.GetString("show_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高强度密码： 的本地化字符串。
        /// </summary>
        internal static string strong_password {
            get {
                return ResourceManager.GetString("strong_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 · 记忆密码：选择一个与个人信息无关的密码，防止社会工程学破解。 的本地化字符串。
        /// </summary>
        internal static string use_explanation1 {
            get {
                return ResourceManager.GetString("use_explanation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 · 区分代号：用于区别不同用途密码的简短代号，如微信账号可用 &quot;微信&quot;  &quot;wechat&quot; 或 &quot;WX&quot; 等。 的本地化字符串。
        /// </summary>
        internal static string use_explanation2 {
            get {
                return ResourceManager.GetString("use_explanation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特殊符号 的本地化字符串。
        /// </summary>
        internal static string with_character {
            get {
                return ResourceManager.GetString("with_character", resourceCulture);
            }
        }
    }
}
